name: Pokeact CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Lint
      run: yarn lint

    - name: Test
      run: yarn test

    - name: Build
      run: yarn build
      
    - uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }} 
        vercel-org-id: ${{ secrets.ORG_ID}} 
        vercel-project-id: ${{ secrets.PROJECT_ID}}

